version: "3"
services:
  db:
    restart: always
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: gfhfser3
      POSTGRES_USER: megamarket
      POSTGRES_DB: test1

  java-app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test1
    expose:
      - 8080
    ports:
      - "8080:8080"